CREATE TABLE IF NOT EXISTS pools (
    id BIGSERIAL PRIMARY KEY,
    chain_id BIGINT NOT NULL,
    block_number BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    "address" BYTEA NOT NULL,
    base_token BYTEA NOT NULL,
    quote_token BYTEA NOT NULL,
    is_token_0 BOOLEAN NOT NULL,
    "type" VARCHAR(255) NOT NULL,
    integrator BYTEA NOT NULL,
    initializer BYTEA NOT NULL,
    fee INT NOT NULL,
    min_threshold NUMERIC,
    max_threshold NUMERIC,
    migrator BYTEA,
    migrated_at TIMESTAMPTZ,
    migration_pool BYTEA,
    migrated_from BYTEA,
    migration_type VARCHAR(10),
    lock_duration INTEGER,
    beneficiaries JSONB,
    pool_key JSONB, 
    starting_time TIMESTAMPTZ NOT NULL,
    ending_time TIMESTAMPTZ NOT NULL,
    source VARCHAR(255) NOT NULL,
    source_version INT NOT NULL,
    UNIQUE (chain_id, address, source, source_version)
);
