ALTER TABLE pool_state ADD COLUMN IF NOT EXISTS amount0 NUMERIC;
ALTER TABLE pool_state ADD COLUMN IF NOT EXISTS amount1 NUMERIC;
ALTER TABLE pool_state ADD COLUMN IF NOT EXISTS tvl_usd NUMERIC;
ALTER TABLE pool_state ADD COLUMN IF NOT EXISTS market_cap_usd NUMERIC;
ALTER TABLE pool_state ADD COLUMN IF NOT EXISTS total_supply NUMERIC;
