CREATE TABLE IF NOT EXISTS pool_metrics (
    id BIGSERIAL PRIMARY KEY,
    chain_id BIGINT NOT NULL,  
    block_number BIGINT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    last_swap_timestamp TIMESTAMPTZ,
    address BYTEA NOT NULL,
    total_fee0 BIGINT NOT NULL,
    total_fee1 BIGINT NOT NULL,
    total_proceeds BIGINT NOT NULL,
    total_tokens_sold BIGINT NOT NULL,
    graduation_balance BIGINT NOT NULL,
    graduation_percentage DOUBLE PRECISION NOT NULL,
    graduation_tick INTEGER,
    reserves0 BIGINT NOT NULL,
    reserves1 BIGINT NOT NULL,
    market_cap_usd BIGINT NOT NULL,
    liquidity_usd BIGINT NOT NULL,
    volume_usd BIGINT NOT NULL,
    tick INTEGER,
    source VARCHAR(255) NOT NULL,
    source_version INT NOT NULL,
    UNIQUE (chain_id, address, timestamp, source, source_version)
)