CREATE TABLE IF NOT EXISTS swaps (
    id BIGSERIAL PRIMARY KEY,
    chain_id BIGINT NOT NULL,
    tx_id BYTEA NOT NULL,
    block_height BIGINT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    pool BYTEA NOT NULL,
    asset BYTEA NOT NULL,
    amountIn BIGINT NOT NULL,
    amountOut BIGINT NOT NULL,
    is_buy BOOLEAN NOT NULL,
    current_tick INTEGER,
    graduation_tick INTEGER,
    fee0_delta BIGINT NOT NULL,
    fee1_delta BIGINT NOT NULL,
    tokens_sold_delta BIGINT NOT NULL,
    graduation_balance_delta BIGINT NOT NULL,
    max_threshold_delta BIGINT NOT NULL,
    market_cap_usd_delta BIGINT NOT NULL,
    liquidity_usd_delta BIGINT NOT NULL,
    value_usd BIGINT NOT NULL,
    log_position BIGINT,
    source VARCHAR(255) NOT NULL,
    source_version INT NOT NULL,
    UNIQUE (chain_id, tx_id, log_position, source, source_version)
);
