CREATE TABLE IF NOT EXISTS tokens (
    id BIGSERIAL PRIMARY KEY,
    chain_id BIGINT NOT NULL,
    block_number BIGINT NOT NULL,
    tx_hash BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    creator_address BYTEA,
    integrator BYTEA,
    address BYTEA NOT NULL,
    pool BYTEA,
    name TEXT NOT NULL,
    symbol TEXT NOT NULL,
    decimals SMALLINT NOT NULL,
    total_supply NUMERIC,
    token_uri TEXT,
    is_derc20 BOOLEAN NOT NULL,
    is_creator_coin BOOLEAN NOT NULL,
    is_content_coin BOOLEAN NOT NULL,
    creator_coin_pool BYTEA,
    governance BYTEA,
    source VARCHAR(255) NOT NULL,
    source_version INT NOT NULL,
    UNIQUE (chain_id, address, source, source_version)
)