//! S3 manifest and marker system for distributed coordination.
//!
//! In a distributed deployment, multiple services need to know what data exists in S3.
//! This module provides:
//! - Marker files: Written after each upload to signal data availability
//! - S3Manifest: Aggregated view of all available data ranges
//! - ManifestManager: Handles manifest refresh and caching

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::RwLock;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

use super::s3::S3Backend;
use super::{StorageBackend, StorageError};
use crate::types::config::storage::SyncConfig;

/// A sorted, deduplicated set of `(start, end)` block ranges.
///
/// Serializes transparently as `Vec<(u64, u64)>` for backward compatibility
/// with existing S3 manifest JSON.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(transparent)]
pub struct RangeSet(Vec<(u64, u64)>);

impl RangeSet {
    pub fn new() -> Self {
        Self(Vec::new())
    }

    /// Check if a specific `(start, end)` range exists in the set.
    pub fn has(&self, start: u64, end: u64) -> bool {
        self.0.iter().any(|(s, e)| *s == start && *e == end)
    }

    /// Add a range. Duplicates are ignored and the set stays sorted by start.
    pub fn add(&mut self, start: u64, end: u64) {
        if !self.has(start, end) {
            self.0.push((start, end));
            self.0.sort_by_key(|(s, _)| *s);
        }
    }

    /// Iterate over all ranges.
    pub fn iter(&self) -> impl Iterator<Item = &(u64, u64)> {
        self.0.iter()
    }

    /// Returns `true` if the set contains no ranges.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Returns the number of ranges in the set.
    pub fn len(&self) -> usize {
        self.0.len()
    }
}

impl<'a> IntoIterator for &'a RangeSet {
    type Item = &'a (u64, u64);
    type IntoIter = std::slice::Iter<'a, (u64, u64)>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}

/// Marker file written after each successful S3 upload.
///
/// Markers are small (~100 bytes) and signal that a particular range is available.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Marker {
    /// Unix timestamp when the upload completed
    pub uploaded_at: u64,
    /// Identifier of the service that uploaded the data
    pub uploader: String,
    /// S3 key of the uploaded file
    pub file_path: String,
}

impl Marker {
    /// Create a new marker.
    pub fn new(file_path: String, uploader: String) -> Self {
        Self {
            uploaded_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            uploader,
            file_path,
        }
    }

    /// Serialize to JSON bytes.
    pub fn to_bytes(&self) -> Result<Vec<u8>, StorageError> {
        serde_json::to_vec(self).map_err(|e| StorageError::Serialization(e.to_string()))
    }

    /// Deserialize from JSON bytes.
    #[allow(dead_code)]
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, StorageError> {
        serde_json::from_slice(bytes).map_err(|e| StorageError::Serialization(e.to_string()))
    }
}

/// Aggregated manifest of all available data in S3.
///
/// This is periodically generated by aggregating marker files and provides
/// a fast way to query what data exists without listing many marker files.
///
/// # Migration Note
/// The `raw_eth_calls` field was changed from `Vec<(u64, u64)>` to
/// `HashMap<String, Vec<(u64, u64)>>` for per-contract/function granularity.
/// The `#[serde(default)]` attribute ensures old manifests with the Vec format
/// deserialize to an empty HashMap, providing backward compatibility.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct S3Manifest {
    /// Unix timestamp when this manifest was generated
    pub generated_at: u64,
    /// Raw blocks ranges: [(start, end), ...]
    pub raw_blocks: RangeSet,
    /// Raw logs ranges
    pub raw_logs: RangeSet,
    /// Raw receipts ranges
    pub raw_receipts: RangeSet,
    /// Raw eth_calls by contract/function: "contract/function" -> [(start, end), ...]
    #[serde(default)]
    pub raw_eth_calls: HashMap<String, RangeSet>,
    /// Decoded logs by source/event: "source/event" -> [(start, end), ...]
    pub decoded_logs: HashMap<String, RangeSet>,
    /// Decoded eth_calls by source/function
    pub decoded_eth_calls: HashMap<String, RangeSet>,
    /// Factory ranges by collection name
    pub factories: HashMap<String, RangeSet>,
}

#[allow(dead_code)]
impl S3Manifest {
    /// Create a new empty manifest.
    pub fn new() -> Self {
        Self {
            generated_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            ..Default::default()
        }
    }

    /// Serialize to JSON bytes.
    pub fn to_bytes(&self) -> Result<Vec<u8>, StorageError> {
        serde_json::to_vec_pretty(self).map_err(|e| StorageError::Serialization(e.to_string()))
    }

    /// Deserialize from JSON bytes.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, StorageError> {
        serde_json::from_slice(bytes).map_err(|e| StorageError::Serialization(e.to_string()))
    }

    /// Check if a raw eth_calls range exists for a specific contract/function.
    pub fn has_raw_eth_calls_granular(
        &self,
        contract: &str,
        func: &str,
        start: u64,
        end: u64,
    ) -> bool {
        let key = format!("{}/{}", contract, func);
        self.raw_eth_calls
            .get(&key)
            .is_some_and(|rs| rs.has(start, end))
    }

    /// Check if a decoded logs range exists for a source/event.
    pub fn has_decoded_logs(&self, source: &str, event: &str, start: u64, end: u64) -> bool {
        let key = format!("{}/{}", source, event);
        self.decoded_logs
            .get(&key)
            .is_some_and(|rs| rs.has(start, end))
    }

    /// Check if a factory range exists.
    pub fn has_factories(&self, collection: &str, start: u64, end: u64) -> bool {
        self.factories
            .get(collection)
            .is_some_and(|rs| rs.has(start, end))
    }

    /// Check if a decoded eth_calls range exists for a source/function.
    pub fn has_decoded_eth_calls(&self, source: &str, func: &str, start: u64, end: u64) -> bool {
        let key = format!("{}/{}", source, func);
        self.decoded_eth_calls
            .get(&key)
            .is_some_and(|rs| rs.has(start, end))
    }

    /// Return the highest block number across all raw_blocks ranges, if any.
    pub fn max_raw_blocks_block(&self) -> Option<u64> {
        self.raw_blocks.iter().map(|(_, end)| *end).max()
    }

    /// Add a raw eth_calls range for a specific contract/function.
    pub fn add_raw_eth_calls_granular(&mut self, contract: &str, func: &str, start: u64, end: u64) {
        let key = format!("{}/{}", contract, func);
        self.raw_eth_calls.entry(key).or_default().add(start, end);
    }

    /// Add a decoded logs range.
    pub fn add_decoded_logs(&mut self, source: &str, event: &str, start: u64, end: u64) {
        let key = format!("{}/{}", source, event);
        self.decoded_logs.entry(key).or_default().add(start, end);
    }

    /// Add a factory range.
    pub fn add_factories(&mut self, collection: &str, start: u64, end: u64) {
        self.factories
            .entry(collection.to_string())
            .or_default()
            .add(start, end);
    }

    /// Add a decoded eth_calls range.
    pub fn add_decoded_eth_calls(&mut self, source: &str, func: &str, start: u64, end: u64) {
        let key = format!("{}/{}", source, func);
        self.decoded_eth_calls
            .entry(key)
            .or_default()
            .add(start, end);
    }
}

/// Manager for S3 manifest operations.
///
/// Handles:
/// - Reading/writing marker files
/// - Manifest aggregation from markers
/// - Caching and periodic refresh
#[allow(dead_code)]
pub struct ManifestManager {
    s3: S3Backend,
    local_base: PathBuf,
    config: SyncConfig,
    /// Registered chains to refresh
    chains: RwLock<Vec<String>>,
    /// Per-chain cached manifests
    cached: RwLock<HashMap<String, S3Manifest>>,
    /// Last refresh time per chain
    last_refresh: RwLock<HashMap<String, Instant>>,
}

#[allow(dead_code)]
impl ManifestManager {
    /// Create a new ManifestManager.
    pub fn new(s3: S3Backend, local_base: PathBuf, config: SyncConfig) -> Self {
        Self {
            s3,
            local_base,
            config,
            chains: RwLock::new(Vec::new()),
            cached: RwLock::new(HashMap::new()),
            last_refresh: RwLock::new(HashMap::new()),
        }
    }

    /// Register a chain for manifest refresh.
    pub fn register_chain(&self, chain: &str) {
        let mut chains = self.chains.write().unwrap();
        if !chains.contains(&chain.to_string()) {
            chains.push(chain.to_string());
            tracing::debug!("Registered chain {} for manifest refresh", chain);
        }
    }

    /// Get access to the underlying S3 backend.
    pub fn s3_backend(&self) -> &S3Backend {
        &self.s3
    }

    /// Get the sync configuration.
    pub fn config(&self) -> &SyncConfig {
        &self.config
    }

    /// Get the local base path.
    pub fn local_base(&self) -> &PathBuf {
        &self.local_base
    }

    /// Get the marker key for a data file.
    ///
    /// Example: "ethereum/historical/raw/blocks/blocks_0-999.parquet"
    ///       -> "ethereum/markers/raw/blocks/0_999.marker"
    pub fn marker_key(chain: &str, data_type: &str, start: u64, end: u64) -> String {
        format!("{}/markers/{}/{}_{}.marker", chain, data_type, start, end)
    }

    /// Get the manifest key for a chain.
    pub fn manifest_key(chain: &str) -> String {
        format!("{}/manifest.json", chain)
    }

    /// Write a marker file after successful upload.
    pub async fn write_marker(
        &self,
        chain: &str,
        data_type: &str,
        start: u64,
        end: u64,
        file_path: &str,
        uploader: &str,
    ) -> Result<(), StorageError> {
        let marker = Marker::new(file_path.to_string(), uploader.to_string());
        let key = Self::marker_key(chain, data_type, start, end);
        let data = marker.to_bytes()?;

        self.s3.write(&key, &data).await?;

        tracing::debug!("Wrote marker: {}", key);
        Ok(())
    }

    /// Check if a marker exists.
    pub async fn has_marker(
        &self,
        chain: &str,
        data_type: &str,
        start: u64,
        end: u64,
    ) -> Result<bool, StorageError> {
        let key = Self::marker_key(chain, data_type, start, end);
        self.s3.exists(&key).await
    }

    /// Get the cached manifest for the first registered chain (if available).
    pub fn cached_manifest(&self) -> Option<S3Manifest> {
        self.cached.read().unwrap().values().next().cloned()
    }

    /// Get the cached manifest for a specific chain.
    pub fn cached_manifest_for(&self, chain: &str) -> Option<S3Manifest> {
        self.cached.read().unwrap().get(chain).cloned()
    }

    /// Check if the cached manifest is stale for any registered chain.
    pub fn is_stale(&self) -> bool {
        let refresh_interval = Duration::from_secs(self.config.manifest_refresh_secs);
        let chains = self.chains.read().unwrap();
        let last_refresh = self.last_refresh.read().unwrap();

        for chain in chains.iter() {
            match last_refresh.get(chain) {
                Some(t) if t.elapsed() <= refresh_interval => continue,
                _ => return true,
            }
        }
        false
    }

    /// Refresh manifests for all registered chains.
    pub async fn refresh(&self) -> Result<(), StorageError> {
        let chains = self.chains.read().unwrap().clone();
        if chains.is_empty() {
            tracing::debug!("No chains registered for manifest refresh");
            return Ok(());
        }

        for chain in chains {
            self.refresh_for_chain(&chain).await?;
        }
        Ok(())
    }

    /// Refresh manifest for a chain by listing and aggregating markers.
    pub async fn refresh_from_markers(&self, chain: &str) -> Result<(), StorageError> {
        let manifest = self.aggregate_markers(chain).await?;

        // Update cache
        {
            let mut cached = self.cached.write().unwrap();
            cached.insert(chain.to_string(), manifest.clone());
        }

        {
            let mut last = self.last_refresh.write().unwrap();
            last.insert(chain.to_string(), Instant::now());
        }

        // Save to S3 for other services
        self.save_manifest(chain, &manifest).await?;

        Ok(())
    }

    /// Refresh the manifest for a specific chain.
    pub async fn refresh_for_chain(&self, chain: &str) -> Result<(), StorageError> {
        let key = Self::manifest_key(chain);

        let manifest = match self.s3.read(&key).await {
            Ok(data) => {
                let manifest = S3Manifest::from_bytes(&data)?;
                tracing::info!(
                    "Loaded manifest for chain {}: {} blocks, {} logs, {} receipts",
                    chain,
                    manifest.raw_blocks.len(),
                    manifest.raw_logs.len(),
                    manifest.raw_receipts.len()
                );
                manifest
            }
            Err(StorageError::NotFound(_)) => {
                // No manifest file yet - rebuild from markers
                tracing::info!(
                    "No manifest found for chain {}, rebuilding from markers",
                    chain
                );
                return self.refresh_from_markers(chain).await;
            }
            Err(e) => return Err(e),
        };

        {
            let mut cached = self.cached.write().unwrap();
            cached.insert(chain.to_string(), manifest);
        }

        {
            let mut last = self.last_refresh.write().unwrap();
            last.insert(chain.to_string(), Instant::now());
        }

        Ok(())
    }

    /// Save the manifest to S3.
    pub async fn save_manifest(
        &self,
        chain: &str,
        manifest: &S3Manifest,
    ) -> Result<(), StorageError> {
        let key = Self::manifest_key(chain);
        let data = manifest.to_bytes()?;
        self.s3.write(&key, &data).await?;

        // Update cache
        {
            let mut cached = self.cached.write().unwrap();
            cached.insert(chain.to_string(), manifest.clone());
        }

        tracing::info!(
            "Saved manifest for chain {} ({} ranges total)",
            chain,
            manifest.raw_blocks.len() + manifest.raw_logs.len() + manifest.raw_receipts.len()
        );

        Ok(())
    }

    /// Aggregate markers into a manifest for a chain.
    ///
    /// This reads all marker files and builds a complete manifest.
    pub async fn aggregate_markers(&self, chain: &str) -> Result<S3Manifest, StorageError> {
        let mut manifest = S3Manifest::new();

        // Raw blocks: {chain}/markers/raw/blocks/{start}_{end}.marker  (0 segments)
        let prefix = format!("{}/markers/raw/blocks", chain);
        self.aggregate_markers_generic(&prefix, |segments, start, end| {
            if segments.is_empty() {
                manifest.raw_blocks.add(start, end);
            }
        })
        .await?;

        // Raw logs: {chain}/markers/raw/logs/{start}_{end}.marker  (0 segments)
        let prefix = format!("{}/markers/raw/logs", chain);
        self.aggregate_markers_generic(&prefix, |segments, start, end| {
            if segments.is_empty() {
                manifest.raw_logs.add(start, end);
            }
        })
        .await?;

        // Raw receipts: {chain}/markers/raw/receipts/{start}_{end}.marker  (0 segments)
        let prefix = format!("{}/markers/raw/receipts", chain);
        self.aggregate_markers_generic(&prefix, |segments, start, end| {
            if segments.is_empty() {
                manifest.raw_receipts.add(start, end);
            }
        })
        .await?;

        // Raw eth_calls: contract/function/{start}_{end}.marker  (2 segments)
        // Or on_events: contract/function/on_events/{start}_{end}.marker  (3 segments)
        let prefix = format!("{}/markers/raw/eth_calls", chain);
        self.aggregate_markers_generic(&prefix, |segments, start, end| {
            match segments.len() {
                2 => manifest.add_raw_eth_calls_granular(segments[0], segments[1], start, end),
                3 if segments[2] == "on_events" => {
                    let combined = format!("{}/on_events", segments[1]);
                    manifest.add_raw_eth_calls_granular(segments[0], &combined, start, end);
                }
                _ => {}
            }
        })
        .await?;

        // Decoded logs: source/event/{start}_{end}.marker  (2 segments)
        let prefix = format!("{}/markers/decoded/logs", chain);
        self.aggregate_markers_generic(&prefix, |segments, start, end| {
            if segments.len() == 2 {
                manifest.add_decoded_logs(segments[0], segments[1], start, end);
            }
        })
        .await?;

        // Decoded eth_calls: source/function/{start}_{end}.marker  (2 segments)
        let prefix = format!("{}/markers/decoded/eth_calls", chain);
        self.aggregate_markers_generic(&prefix, |segments, start, end| {
            if segments.len() == 2 {
                manifest.add_decoded_eth_calls(segments[0], segments[1], start, end);
            }
        })
        .await?;

        // Factories: collection/{start}_{end}.marker  (1 segment)
        let prefix = format!("{}/markers/factories", chain);
        self.aggregate_markers_generic(&prefix, |segments, start, end| {
            if segments.len() == 1 {
                manifest.add_factories(segments[0], start, end);
            }
        })
        .await?;

        Ok(manifest)
    }

    /// Generic helper to list S3 markers under a prefix and invoke a callback
    /// with the parsed path segments (excluding the marker filename) and the
    /// `(start, end)` range extracted from the filename.
    ///
    /// The callback receives `(&[&str], u64, u64)` where the slice contains the
    /// path segments between the prefix and the marker file.  Each aggregation
    /// call-site filters on the expected segment count and extracts names as
    /// needed, keeping the S3-list + parse logic in one place.
    async fn aggregate_markers_generic<F>(
        &self,
        prefix: &str,
        mut on_marker: F,
    ) -> Result<(), StorageError>
    where
        F: FnMut(&[&str], u64, u64),
    {
        let all_entries = self.s3.list(prefix).await?;
        for entry in all_entries {
            let parts: Vec<&str> = entry.split('/').collect();
            if parts.is_empty() {
                continue;
            }
            // The last segment is always the marker filename
            let marker_filename = parts[parts.len() - 1];
            if let Some((start, end)) = parse_marker_filename(marker_filename) {
                let segments = &parts[..parts.len() - 1];
                on_marker(segments, start, end);
            }
        }
        Ok(())
    }
}

/// Parse a marker filename like "0_999.marker" into (start, end).
fn parse_marker_filename(filename: &str) -> Option<(u64, u64)> {
    let name = filename.trim_end_matches(".marker");
    let parts: Vec<&str> = name.split('_').collect();
    if parts.len() == 2 {
        let start = parts[0].parse().ok()?;
        let end = parts[1].parse().ok()?;
        return Some((start, end));
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_marker_serialization() {
        let marker = Marker::new(
            "ethereum/historical/raw/blocks/blocks_0-999.parquet".to_string(),
            "collector-01".to_string(),
        );

        let bytes = marker.to_bytes().unwrap();
        let parsed = Marker::from_bytes(&bytes).unwrap();

        assert_eq!(parsed.file_path, marker.file_path);
        assert_eq!(parsed.uploader, marker.uploader);
    }

    // =========================================================================
    // RangeSet tests
    // =========================================================================

    #[test]
    fn test_range_set_has() {
        let mut rs = RangeSet::new();
        rs.add(0, 100);
        assert!(rs.has(0, 100));
        assert!(!rs.has(0, 50));
    }

    #[test]
    fn test_range_set_add_idempotent() {
        let mut rs = RangeSet::new();
        rs.add(0, 100);
        rs.add(0, 100);
        assert_eq!(rs.len(), 1);
    }

    #[test]
    fn test_range_set_sorted() {
        let mut rs = RangeSet::new();
        rs.add(200, 300);
        rs.add(0, 100);
        let ranges: Vec<_> = rs.iter().collect();
        assert_eq!(ranges[0].0, 0);
        assert_eq!(ranges[1].0, 200);
    }

    #[test]
    fn test_range_set_serde_roundtrip() {
        let mut rs = RangeSet::new();
        rs.add(0, 100);
        rs.add(200, 300);
        let json = serde_json::to_string(&rs).unwrap();
        let deserialized: RangeSet = serde_json::from_str(&json).unwrap();
        assert!(deserialized.has(0, 100));
        assert!(deserialized.has(200, 300));
        // Verify it serializes as a plain array (transparent)
        let value: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert!(value.is_array());
    }

    #[test]
    fn test_range_set_empty() {
        let rs = RangeSet::new();
        assert!(rs.is_empty());
        assert_eq!(rs.len(), 0);
        assert!(!rs.has(0, 100));
    }

    #[test]
    fn test_manifest_add_ranges() {
        let mut manifest = S3Manifest::new();

        manifest.raw_blocks.add(0, 999);
        manifest.raw_blocks.add(1000, 1999);
        manifest.raw_blocks.add(0, 999); // Duplicate

        assert_eq!(manifest.raw_blocks.len(), 2);
        assert!(manifest.raw_blocks.has(0, 999));
        assert!(manifest.raw_blocks.has(1000, 1999));
        assert!(!manifest.raw_blocks.has(2000, 2999));
    }

    #[test]
    fn test_manifest_decoded_logs() {
        let mut manifest = S3Manifest::new();

        manifest.add_decoded_logs("v3", "Swap", 0, 999);
        manifest.add_decoded_logs("v3", "Burn", 0, 999);

        assert!(manifest.has_decoded_logs("v3", "Swap", 0, 999));
        assert!(manifest.has_decoded_logs("v3", "Burn", 0, 999));
        assert!(!manifest.has_decoded_logs("v3", "Swap", 1000, 1999));
    }

    #[test]
    fn test_marker_key() {
        let key = ManifestManager::marker_key("ethereum", "raw/blocks", 0, 999);
        assert_eq!(key, "ethereum/markers/raw/blocks/0_999.marker");
    }

    #[test]
    fn test_parse_marker_filename() {
        assert_eq!(parse_marker_filename("0_999.marker"), Some((0, 999)));
        assert_eq!(
            parse_marker_filename("1000_1999.marker"),
            Some((1000, 1999))
        );
        assert_eq!(parse_marker_filename("invalid.marker"), None);
    }

    use std::sync::Arc;

    use object_store::memory::InMemory;

    fn create_test_manager() -> ManifestManager {
        let store = Arc::new(InMemory::new());
        let s3 = S3Backend::from_store(store, "test-bucket".to_string());
        ManifestManager::new(s3, PathBuf::from("/tmp/test"), SyncConfig::default())
    }

    /// Write a marker file to the in-memory S3 backend at the given key.
    async fn write_marker_at(manager: &ManifestManager, key: &str) {
        let marker = Marker::new(format!("data/{}", key), "test".to_string());
        let data = marker.to_bytes().unwrap();
        manager.s3.write(key, &data).await.unwrap();
    }

    #[tokio::test]
    async fn test_aggregate_nested_markers_flat_parsing() {
        let manager = create_test_manager();

        // Write markers at the flat paths that S3 list returns relative to prefix
        let prefix = "eth/markers/decoded/logs";
        write_marker_at(&manager, &format!("{}/v3/Swap/0_999.marker", prefix)).await;
        write_marker_at(&manager, &format!("{}/v3/Swap/1000_1999.marker", prefix)).await;
        write_marker_at(&manager, &format!("{}/v3/Burn/0_999.marker", prefix)).await;
        write_marker_at(&manager, &format!("{}/v4/Transfer/500_1499.marker", prefix)).await;

        let mut results: Vec<(String, String, u64, u64)> = Vec::new();
        manager
            .aggregate_markers_generic(prefix, |segments, start, end| {
                if segments.len() == 2 {
                    results.push((segments[0].to_string(), segments[1].to_string(), start, end));
                }
            })
            .await
            .unwrap();

        results.sort_by(|a, b| (&a.0, &a.1, a.2).cmp(&(&b.0, &b.1, b.2)));

        assert_eq!(results.len(), 4);
        assert_eq!(results[0], ("v3".to_string(), "Burn".to_string(), 0, 999));
        assert_eq!(results[1], ("v3".to_string(), "Swap".to_string(), 0, 999));
        assert_eq!(
            results[2],
            ("v3".to_string(), "Swap".to_string(), 1000, 1999)
        );
        assert_eq!(
            results[3],
            ("v4".to_string(), "Transfer".to_string(), 500, 1499)
        );
    }

    #[tokio::test]
    async fn test_aggregate_factory_markers_flat_parsing() {
        let manager = create_test_manager();

        let prefix = "eth/markers/factories";
        write_marker_at(
            &manager,
            &format!("{}/pool_collection/0_999.marker", prefix),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/pool_collection/1000_1999.marker", prefix),
        )
        .await;
        write_marker_at(&manager, &format!("{}/token_pairs/0_999.marker", prefix)).await;

        let mut results: Vec<(String, u64, u64)> = Vec::new();
        manager
            .aggregate_markers_generic(prefix, |segments, start, end| {
                if segments.len() == 1 {
                    results.push((segments[0].to_string(), start, end));
                }
            })
            .await
            .unwrap();

        results.sort_by(|a, b| (&a.0, a.1).cmp(&(&b.0, b.1)));

        assert_eq!(results.len(), 3);
        assert_eq!(results[0], ("pool_collection".to_string(), 0, 999));
        assert_eq!(results[1], ("pool_collection".to_string(), 1000, 1999));
        assert_eq!(results[2], ("token_pairs".to_string(), 0, 999));
    }

    #[tokio::test]
    async fn test_aggregate_eth_call_markers_regular_and_on_events() {
        let manager = create_test_manager();

        let prefix = "eth/markers/raw/eth_calls";
        // Regular: contract/function/start_end.marker
        write_marker_at(&manager, &format!("{}/0xabc/getPrice/0_999.marker", prefix)).await;
        write_marker_at(
            &manager,
            &format!("{}/0xabc/getPrice/1000_1999.marker", prefix),
        )
        .await;
        // On events: contract/function/on_events/start_end.marker
        write_marker_at(
            &manager,
            &format!("{}/0xdef/getLiquidity/on_events/0_999.marker", prefix),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/0xdef/getLiquidity/on_events/1000_1999.marker", prefix),
        )
        .await;

        let mut results: Vec<(String, String, u64, u64)> = Vec::new();
        manager
            .aggregate_markers_generic(prefix, |segments, start, end| {
                match segments.len() {
                    2 => results.push((
                        segments[0].to_string(),
                        segments[1].to_string(),
                        start,
                        end,
                    )),
                    3 if segments[2] == "on_events" => {
                        let combined = format!("{}/on_events", segments[1]);
                        results.push((segments[0].to_string(), combined, start, end));
                    }
                    _ => {}
                }
            })
            .await
            .unwrap();

        results.sort_by(|a, b| (&a.0, &a.1, a.2).cmp(&(&b.0, &b.1, b.2)));

        assert_eq!(results.len(), 4);
        assert_eq!(
            results[0],
            ("0xabc".to_string(), "getPrice".to_string(), 0, 999)
        );
        assert_eq!(
            results[1],
            ("0xabc".to_string(), "getPrice".to_string(), 1000, 1999)
        );
        assert_eq!(
            results[2],
            (
                "0xdef".to_string(),
                "getLiquidity/on_events".to_string(),
                0,
                999
            )
        );
        assert_eq!(
            results[3],
            (
                "0xdef".to_string(),
                "getLiquidity/on_events".to_string(),
                1000,
                1999
            )
        );
    }

    #[tokio::test]
    async fn test_aggregate_markers_generic_propagates_errors() {
        // The InMemory store returns an empty list (not an error) for empty prefix,
        // so we test that the `?` propagation works by verifying non-error case succeeds.
        // The key behavioral change is that unwrap_or_default() is replaced with ?,
        // so real S3 errors bubble up instead of being silently swallowed.
        let manager = create_test_manager();

        // No markers written - should return Ok with empty results
        let mut results: Vec<(u64, u64)> = Vec::new();
        let result = manager
            .aggregate_markers_generic("nonexistent/prefix", |segments, start, end| {
                if segments.is_empty() {
                    results.push((start, end));
                }
            })
            .await;

        assert!(result.is_ok());
        assert!(results.is_empty());
    }

    #[tokio::test]
    async fn test_aggregate_markers_full_chain() {
        let manager = create_test_manager();

        // Write markers for various data types
        let chain = "ethereum";

        // Raw blocks
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/blocks/0_999.marker", chain),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/blocks/1000_1999.marker", chain),
        )
        .await;

        // Raw logs
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/logs/0_999.marker", chain),
        )
        .await;

        // Decoded logs (nested: source/event/marker)
        write_marker_at(
            &manager,
            &format!("{}/markers/decoded/logs/v3/Swap/0_999.marker", chain),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/markers/decoded/logs/v3/Burn/0_999.marker", chain),
        )
        .await;

        // Factories
        write_marker_at(
            &manager,
            &format!("{}/markers/factories/pools/0_999.marker", chain),
        )
        .await;

        // Raw eth_calls with on_events
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/eth_calls/0xabc/slot0/0_999.marker", chain),
        )
        .await;
        write_marker_at(
            &manager,
            &format!(
                "{}/markers/raw/eth_calls/0xabc/slot0/on_events/0_999.marker",
                chain
            ),
        )
        .await;

        let manifest = manager.aggregate_markers(chain).await.unwrap();

        assert_eq!(manifest.raw_blocks.len(), 2);
        assert!(manifest.raw_blocks.has(0, 999));
        assert!(manifest.raw_blocks.has(1000, 1999));

        assert_eq!(manifest.raw_logs.len(), 1);
        assert!(manifest.raw_logs.has(0, 999));

        assert!(manifest.has_decoded_logs("v3", "Swap", 0, 999));
        assert!(manifest.has_decoded_logs("v3", "Burn", 0, 999));

        assert!(manifest.has_factories("pools", 0, 999));

        assert!(manifest.has_raw_eth_calls_granular("0xabc", "slot0", 0, 999));
        assert!(manifest.has_raw_eth_calls_granular("0xabc", "slot0/on_events", 0, 999));
    }

    #[tokio::test]
    async fn test_refresh_for_chain_rebuilds_from_markers_when_no_manifest() {
        let manager = create_test_manager();
        let chain = "ethereum";

        // Write some markers but NO manifest.json
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/blocks/0_999.marker", chain),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/blocks/1000_1999.marker", chain),
        )
        .await;

        // refresh_for_chain should detect missing manifest and rebuild from markers
        manager.refresh_for_chain(chain).await.unwrap();

        let cached = manager.cached_manifest_for(chain);
        assert!(cached.is_some());

        let manifest = cached.unwrap();
        assert_eq!(manifest.raw_blocks.len(), 2);
        assert!(manifest.raw_blocks.has(0, 999));
        assert!(manifest.raw_blocks.has(1000, 1999));

        // Verify manifest.json was saved to S3
        let key = ManifestManager::manifest_key(chain);
        let data = manager.s3.read(&key).await.unwrap();
        let saved_manifest = S3Manifest::from_bytes(&data).unwrap();
        assert_eq!(saved_manifest.raw_blocks.len(), 2);
    }

    #[tokio::test]
    async fn test_nested_markers_ignores_wrong_depth_entries() {
        let manager = create_test_manager();

        let prefix = "eth/markers/decoded/logs";
        // Correct depth (2 segments: source/item)
        write_marker_at(&manager, &format!("{}/v3/Swap/0_999.marker", prefix)).await;
        // Wrong depth (0 segments - just a marker at root level)
        write_marker_at(&manager, &format!("{}/0_999.marker", prefix)).await;

        let mut results: Vec<(String, String, u64, u64)> = Vec::new();
        manager
            .aggregate_markers_generic(prefix, |segments, start, end| {
                if segments.len() == 2 {
                    results.push((segments[0].to_string(), segments[1].to_string(), start, end));
                }
            })
            .await
            .unwrap();

        // Only the correctly-nested entry should be picked up
        assert_eq!(results.len(), 1);
        assert_eq!(results[0], ("v3".to_string(), "Swap".to_string(), 0, 999));
    }
}
