//! S3 manifest and marker system for distributed coordination.
//!
//! In a distributed deployment, multiple services need to know what data exists in S3.
//! This module provides:
//! - Marker files: Written after each upload to signal data availability
//! - S3Manifest: Aggregated view of all available data ranges
//! - ManifestManager: Handles manifest refresh and caching

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::RwLock;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

use super::s3::S3Backend;
use super::{StorageBackend, StorageError};
use crate::types::config::storage::SyncConfig;

/// Marker file written after each successful S3 upload.
///
/// Markers are small (~100 bytes) and signal that a particular range is available.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Marker {
    /// Unix timestamp when the upload completed
    pub uploaded_at: u64,
    /// Identifier of the service that uploaded the data
    pub uploader: String,
    /// S3 key of the uploaded file
    pub file_path: String,
}

impl Marker {
    /// Create a new marker.
    pub fn new(file_path: String, uploader: String) -> Self {
        Self {
            uploaded_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            uploader,
            file_path,
        }
    }

    /// Serialize to JSON bytes.
    pub fn to_bytes(&self) -> Result<Vec<u8>, StorageError> {
        serde_json::to_vec(self).map_err(|e| StorageError::Serialization(e.to_string()))
    }

    /// Deserialize from JSON bytes.
    #[allow(dead_code)]
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, StorageError> {
        serde_json::from_slice(bytes).map_err(|e| StorageError::Serialization(e.to_string()))
    }
}

/// Aggregated manifest of all available data in S3.
///
/// This is periodically generated by aggregating marker files and provides
/// a fast way to query what data exists without listing many marker files.
///
/// # Migration Note
/// The `raw_eth_calls` field was changed from `Vec<(u64, u64)>` to
/// `HashMap<String, Vec<(u64, u64)>>` for per-contract/function granularity.
/// The `#[serde(default)]` attribute ensures old manifests with the Vec format
/// deserialize to an empty HashMap, providing backward compatibility.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct S3Manifest {
    /// Unix timestamp when this manifest was generated
    pub generated_at: u64,
    /// Raw blocks ranges: [(start, end), ...]
    pub raw_blocks: Vec<(u64, u64)>,
    /// Raw logs ranges
    pub raw_logs: Vec<(u64, u64)>,
    /// Raw receipts ranges
    pub raw_receipts: Vec<(u64, u64)>,
    /// Raw eth_calls by contract/function: "contract/function" -> [(start, end), ...]
    #[serde(default)]
    pub raw_eth_calls: HashMap<String, Vec<(u64, u64)>>,
    /// Decoded logs by source/event: "source/event" -> [(start, end), ...]
    pub decoded_logs: HashMap<String, Vec<(u64, u64)>>,
    /// Decoded eth_calls by source/function
    pub decoded_eth_calls: HashMap<String, Vec<(u64, u64)>>,
    /// Factory ranges by collection name
    pub factories: HashMap<String, Vec<(u64, u64)>>,
}

#[allow(dead_code)]
impl S3Manifest {
    /// Create a new empty manifest.
    pub fn new() -> Self {
        Self {
            generated_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            ..Default::default()
        }
    }

    /// Serialize to JSON bytes.
    pub fn to_bytes(&self) -> Result<Vec<u8>, StorageError> {
        serde_json::to_vec_pretty(self).map_err(|e| StorageError::Serialization(e.to_string()))
    }

    /// Deserialize from JSON bytes.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, StorageError> {
        serde_json::from_slice(bytes).map_err(|e| StorageError::Serialization(e.to_string()))
    }

    /// Check if a raw blocks range exists in the manifest.
    pub fn has_raw_blocks(&self, start: u64, end: u64) -> bool {
        self.raw_blocks
            .iter()
            .any(|(s, e)| *s == start && *e == end)
    }

    /// Check if a raw logs range exists.
    pub fn has_raw_logs(&self, start: u64, end: u64) -> bool {
        self.raw_logs.iter().any(|(s, e)| *s == start && *e == end)
    }

    /// Check if a raw receipts range exists.
    pub fn has_raw_receipts(&self, start: u64, end: u64) -> bool {
        self.raw_receipts
            .iter()
            .any(|(s, e)| *s == start && *e == end)
    }

    /// Check if a raw eth_calls range exists for a specific contract/function.
    pub fn has_raw_eth_calls_granular(
        &self,
        contract: &str,
        func: &str,
        start: u64,
        end: u64,
    ) -> bool {
        let key = format!("{}/{}", contract, func);
        self.raw_eth_calls
            .get(&key)
            .map(|ranges| ranges.iter().any(|(s, e)| *s == start && *e == end))
            .unwrap_or(false)
    }

    /// Check if a decoded logs range exists for a source/event.
    pub fn has_decoded_logs(&self, source: &str, event: &str, start: u64, end: u64) -> bool {
        let key = format!("{}/{}", source, event);
        self.decoded_logs
            .get(&key)
            .map(|ranges| ranges.iter().any(|(s, e)| *s == start && *e == end))
            .unwrap_or(false)
    }

    /// Check if a factory range exists.
    pub fn has_factories(&self, collection: &str, start: u64, end: u64) -> bool {
        self.factories
            .get(collection)
            .map(|ranges| ranges.iter().any(|(s, e)| *s == start && *e == end))
            .unwrap_or(false)
    }

    /// Check if a decoded eth_calls range exists for a source/function.
    pub fn has_decoded_eth_calls(&self, source: &str, func: &str, start: u64, end: u64) -> bool {
        let key = format!("{}/{}", source, func);
        self.decoded_eth_calls
            .get(&key)
            .map(|ranges| ranges.iter().any(|(s, e)| *s == start && *e == end))
            .unwrap_or(false)
    }

    /// Return the highest block number across all raw_blocks ranges, if any.
    pub fn max_raw_blocks_block(&self) -> Option<u64> {
        self.raw_blocks.iter().map(|(_, end)| *end).max()
    }

    /// Add a raw blocks range.
    pub fn add_raw_blocks(&mut self, start: u64, end: u64) {
        if !self.has_raw_blocks(start, end) {
            self.raw_blocks.push((start, end));
            self.raw_blocks.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a raw logs range.
    pub fn add_raw_logs(&mut self, start: u64, end: u64) {
        if !self.has_raw_logs(start, end) {
            self.raw_logs.push((start, end));
            self.raw_logs.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a raw receipts range.
    pub fn add_raw_receipts(&mut self, start: u64, end: u64) {
        if !self.has_raw_receipts(start, end) {
            self.raw_receipts.push((start, end));
            self.raw_receipts.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a raw eth_calls range for a specific contract/function.
    pub fn add_raw_eth_calls_granular(&mut self, contract: &str, func: &str, start: u64, end: u64) {
        let key = format!("{}/{}", contract, func);
        let ranges = self.raw_eth_calls.entry(key).or_default();
        if !ranges.iter().any(|(s, e)| *s == start && *e == end) {
            ranges.push((start, end));
            ranges.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a decoded logs range.
    pub fn add_decoded_logs(&mut self, source: &str, event: &str, start: u64, end: u64) {
        let key = format!("{}/{}", source, event);
        let ranges = self.decoded_logs.entry(key).or_default();
        if !ranges.iter().any(|(s, e)| *s == start && *e == end) {
            ranges.push((start, end));
            ranges.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a factory range.
    pub fn add_factories(&mut self, collection: &str, start: u64, end: u64) {
        let ranges = self.factories.entry(collection.to_string()).or_default();
        if !ranges.iter().any(|(s, e)| *s == start && *e == end) {
            ranges.push((start, end));
            ranges.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a decoded eth_calls range.
    pub fn add_decoded_eth_calls(&mut self, source: &str, func: &str, start: u64, end: u64) {
        let key = format!("{}/{}", source, func);
        let ranges = self.decoded_eth_calls.entry(key).or_default();
        if !ranges.iter().any(|(s, e)| *s == start && *e == end) {
            ranges.push((start, end));
            ranges.sort_by_key(|(s, _)| *s);
        }
    }
}

/// Manager for S3 manifest operations.
///
/// Handles:
/// - Reading/writing marker files
/// - Manifest aggregation from markers
/// - Caching and periodic refresh
#[allow(dead_code)]
pub struct ManifestManager {
    s3: S3Backend,
    local_base: PathBuf,
    config: SyncConfig,
    /// Registered chains to refresh
    chains: RwLock<Vec<String>>,
    /// Per-chain cached manifests
    cached: RwLock<HashMap<String, S3Manifest>>,
    /// Last refresh time per chain
    last_refresh: RwLock<HashMap<String, Instant>>,
}

#[allow(dead_code)]
impl ManifestManager {
    /// Create a new ManifestManager.
    pub fn new(s3: S3Backend, local_base: PathBuf, config: SyncConfig) -> Self {
        Self {
            s3,
            local_base,
            config,
            chains: RwLock::new(Vec::new()),
            cached: RwLock::new(HashMap::new()),
            last_refresh: RwLock::new(HashMap::new()),
        }
    }

    /// Register a chain for manifest refresh.
    pub fn register_chain(&self, chain: &str) {
        let mut chains = self.chains.write().unwrap();
        if !chains.contains(&chain.to_string()) {
            chains.push(chain.to_string());
            tracing::debug!("Registered chain {} for manifest refresh", chain);
        }
    }

    /// Get access to the underlying S3 backend.
    pub fn s3_backend(&self) -> &S3Backend {
        &self.s3
    }

    /// Get the sync configuration.
    pub fn config(&self) -> &SyncConfig {
        &self.config
    }

    /// Get the local base path.
    pub fn local_base(&self) -> &PathBuf {
        &self.local_base
    }

    /// Get the marker key for a data file.
    ///
    /// Example: "ethereum/historical/raw/blocks/blocks_0-999.parquet"
    ///       -> "ethereum/markers/raw/blocks/0_999.marker"
    pub fn marker_key(chain: &str, data_type: &str, start: u64, end: u64) -> String {
        format!("{}/markers/{}/{}_{}.marker", chain, data_type, start, end)
    }

    /// Get the manifest key for a chain.
    pub fn manifest_key(chain: &str) -> String {
        format!("{}/manifest.json", chain)
    }

    /// Write a marker file after successful upload.
    pub async fn write_marker(
        &self,
        chain: &str,
        data_type: &str,
        start: u64,
        end: u64,
        file_path: &str,
        uploader: &str,
    ) -> Result<(), StorageError> {
        let marker = Marker::new(file_path.to_string(), uploader.to_string());
        let key = Self::marker_key(chain, data_type, start, end);
        let data = marker.to_bytes()?;

        self.s3.write(&key, &data).await?;

        tracing::debug!("Wrote marker: {}", key);
        Ok(())
    }

    /// Check if a marker exists.
    pub async fn has_marker(
        &self,
        chain: &str,
        data_type: &str,
        start: u64,
        end: u64,
    ) -> Result<bool, StorageError> {
        let key = Self::marker_key(chain, data_type, start, end);
        self.s3.exists(&key).await
    }

    /// Get the cached manifest for the first registered chain (if available).
    pub fn cached_manifest(&self) -> Option<S3Manifest> {
        self.cached.read().unwrap().values().next().cloned()
    }

    /// Get the cached manifest for a specific chain.
    pub fn cached_manifest_for(&self, chain: &str) -> Option<S3Manifest> {
        self.cached.read().unwrap().get(chain).cloned()
    }

    /// Check if the cached manifest is stale for any registered chain.
    pub fn is_stale(&self) -> bool {
        let refresh_interval = Duration::from_secs(self.config.manifest_refresh_secs);
        let chains = self.chains.read().unwrap();
        let last_refresh = self.last_refresh.read().unwrap();

        for chain in chains.iter() {
            match last_refresh.get(chain) {
                Some(t) if t.elapsed() <= refresh_interval => continue,
                _ => return true,
            }
        }
        false
    }

    /// Refresh manifests for all registered chains.
    pub async fn refresh(&self) -> Result<(), StorageError> {
        let chains = self.chains.read().unwrap().clone();
        if chains.is_empty() {
            tracing::debug!("No chains registered for manifest refresh");
            return Ok(());
        }

        for chain in chains {
            self.refresh_for_chain(&chain).await?;
        }
        Ok(())
    }

    /// Refresh manifest for a chain by listing and aggregating markers.
    pub async fn refresh_from_markers(&self, chain: &str) -> Result<(), StorageError> {
        let manifest = self.aggregate_markers(chain).await?;

        // Update cache
        {
            let mut cached = self.cached.write().unwrap();
            cached.insert(chain.to_string(), manifest.clone());
        }

        {
            let mut last = self.last_refresh.write().unwrap();
            last.insert(chain.to_string(), Instant::now());
        }

        // Save to S3 for other services
        self.save_manifest(chain, &manifest).await?;

        Ok(())
    }

    /// Refresh the manifest for a specific chain.
    pub async fn refresh_for_chain(&self, chain: &str) -> Result<(), StorageError> {
        let key = Self::manifest_key(chain);

        let manifest = match self.s3.read(&key).await {
            Ok(data) => {
                let manifest = S3Manifest::from_bytes(&data)?;
                tracing::info!(
                    "Loaded manifest for chain {}: {} blocks, {} logs, {} receipts",
                    chain,
                    manifest.raw_blocks.len(),
                    manifest.raw_logs.len(),
                    manifest.raw_receipts.len()
                );
                manifest
            }
            Err(StorageError::NotFound(_)) => {
                // No manifest file yet - rebuild from markers
                tracing::info!(
                    "No manifest found for chain {}, rebuilding from markers",
                    chain
                );
                return self.refresh_from_markers(chain).await;
            }
            Err(e) => return Err(e),
        };

        {
            let mut cached = self.cached.write().unwrap();
            cached.insert(chain.to_string(), manifest);
        }

        {
            let mut last = self.last_refresh.write().unwrap();
            last.insert(chain.to_string(), Instant::now());
        }

        Ok(())
    }

    /// Save the manifest to S3.
    pub async fn save_manifest(
        &self,
        chain: &str,
        manifest: &S3Manifest,
    ) -> Result<(), StorageError> {
        let key = Self::manifest_key(chain);
        let data = manifest.to_bytes()?;
        self.s3.write(&key, &data).await?;

        // Update cache
        {
            let mut cached = self.cached.write().unwrap();
            cached.insert(chain.to_string(), manifest.clone());
        }

        tracing::info!(
            "Saved manifest for chain {} ({} ranges total)",
            chain,
            manifest.raw_blocks.len() + manifest.raw_logs.len() + manifest.raw_receipts.len()
        );

        Ok(())
    }

    /// Aggregate markers into a manifest for a chain.
    ///
    /// This reads all marker files and builds a complete manifest.
    pub async fn aggregate_markers(&self, chain: &str) -> Result<S3Manifest, StorageError> {
        let mut manifest = S3Manifest::new();

        // List and parse raw block markers
        let marker_prefix = format!("{}/markers/raw/blocks", chain);
        self.aggregate_raw_markers(&marker_prefix, |start, end| {
            manifest.add_raw_blocks(start, end);
        })
        .await?;

        // List and parse raw log markers
        let marker_prefix = format!("{}/markers/raw/logs", chain);
        self.aggregate_raw_markers(&marker_prefix, |start, end| {
            manifest.add_raw_logs(start, end);
        })
        .await?;

        // List and parse raw receipt markers
        let marker_prefix = format!("{}/markers/raw/receipts", chain);
        self.aggregate_raw_markers(&marker_prefix, |start, end| {
            manifest.add_raw_receipts(start, end);
        })
        .await?;

        // Aggregate raw eth_calls: {chain}/markers/raw/eth_calls/{contract}/{function}/
        // Also handles on_events: {chain}/markers/raw/eth_calls/{contract}/{function}/on_events/
        let prefix = format!("{}/markers/raw/eth_calls", chain);
        self.aggregate_eth_call_markers(&prefix, &mut |contract, func, start, end| {
            manifest.add_raw_eth_calls_granular(contract, func, start, end);
        })
        .await?;

        // Aggregate decoded logs: {chain}/markers/decoded/logs/{source}/{event}/
        let prefix = format!("{}/markers/decoded/logs", chain);
        self.aggregate_nested_markers(&prefix, &mut |source, event, start, end| {
            manifest.add_decoded_logs(source, event, start, end);
        })
        .await?;

        // Aggregate decoded eth_calls: {chain}/markers/decoded/eth_calls/{source}/{fn}/
        let prefix = format!("{}/markers/decoded/eth_calls", chain);
        self.aggregate_nested_markers(&prefix, &mut |source, func, start, end| {
            manifest.add_decoded_eth_calls(source, func, start, end);
        })
        .await?;

        // Aggregate factories: {chain}/markers/factories/{collection}/
        let prefix = format!("{}/markers/factories", chain);
        self.aggregate_factory_markers(&prefix, &mut |collection, start, end| {
            manifest.add_factories(collection, start, end);
        })
        .await?;

        Ok(manifest)
    }

    /// Helper to aggregate markers for a single data type.
    ///
    /// Lists all entries under the prefix and parses marker filenames directly.
    /// The S3 list call returns flat relative paths like "0_999.marker".
    async fn aggregate_raw_markers<F>(
        &self,
        prefix: &str,
        mut add_fn: F,
    ) -> Result<(), StorageError>
    where
        F: FnMut(u64, u64),
    {
        let markers = self.s3.list(prefix).await?;

        for marker_file in markers {
            // Parse range from filename like "0_999.marker"
            if let Some(range) = parse_marker_filename(&marker_file) {
                add_fn(range.0, range.1);
            }
        }

        Ok(())
    }

    /// Helper to aggregate nested markers (source/item structure like decoded logs).
    ///
    /// Uses a single flat list call and parses paths locally.
    /// S3 list returns flat relative paths like "v3/Swap/0_999.marker",
    /// which we split into source ("v3"), item ("Swap"), and marker filename.
    async fn aggregate_nested_markers<F>(
        &self,
        prefix: &str,
        add_fn: &mut F,
    ) -> Result<(), StorageError>
    where
        F: FnMut(&str, &str, u64, u64),
    {
        let all_entries = self.s3.list(prefix).await?;
        for entry in all_entries {
            let parts: Vec<&str> = entry.split('/').collect();
            // Expect: source/item/start_end.marker
            if parts.len() == 3 {
                if let Some((start, end)) = parse_marker_filename(parts[2]) {
                    add_fn(parts[0], parts[1], start, end);
                }
            }
        }
        Ok(())
    }

    /// Helper to aggregate factory markers (collection structure).
    ///
    /// Uses a single flat list call and parses paths locally.
    /// S3 list returns flat relative paths like "poolcollection/0_999.marker",
    /// which we split into collection name and marker filename.
    async fn aggregate_factory_markers<F>(
        &self,
        prefix: &str,
        add_fn: &mut F,
    ) -> Result<(), StorageError>
    where
        F: FnMut(&str, u64, u64),
    {
        let all_entries = self.s3.list(prefix).await?;
        for entry in all_entries {
            let parts: Vec<&str> = entry.split('/').collect();
            // Expect: collection/start_end.marker
            if parts.len() == 2 {
                if let Some((start, end)) = parse_marker_filename(parts[1]) {
                    add_fn(parts[0], start, end);
                }
            }
        }
        Ok(())
    }

    /// Helper to aggregate eth_call markers with up to 4 levels of nesting.
    ///
    /// Uses a single flat list call and parses paths locally.
    /// S3 list returns flat relative paths, which we split by '/'.
    ///
    /// Handles both:
    /// - Regular (3 parts): contract/function/start_end.marker
    /// - On events (4 parts): contract/function/on_events/start_end.marker
    ///
    /// Keys are formatted as "contract/function" or "contract/function/on_events".
    async fn aggregate_eth_call_markers<F>(
        &self,
        prefix: &str,
        add_fn: &mut F,
    ) -> Result<(), StorageError>
    where
        F: FnMut(&str, &str, u64, u64),
    {
        let all_entries = self.s3.list(prefix).await?;
        for entry in all_entries {
            let parts: Vec<&str> = entry.split('/').collect();
            match parts.len() {
                // contract/function/start_end.marker
                3 => {
                    if let Some((start, end)) = parse_marker_filename(parts[2]) {
                        add_fn(parts[0], parts[1], start, end);
                    }
                }
                // contract/function/on_events/start_end.marker
                4 if parts[2] == "on_events" => {
                    if let Some((start, end)) = parse_marker_filename(parts[3]) {
                        let combined_func = format!("{}/on_events", parts[1]);
                        add_fn(parts[0], &combined_func, start, end);
                    }
                }
                _ => {}
            }
        }
        Ok(())
    }
}

/// Parse a marker filename like "0_999.marker" into (start, end).
fn parse_marker_filename(filename: &str) -> Option<(u64, u64)> {
    let name = filename.trim_end_matches(".marker");
    let parts: Vec<&str> = name.split('_').collect();
    if parts.len() == 2 {
        let start = parts[0].parse().ok()?;
        let end = parts[1].parse().ok()?;
        return Some((start, end));
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_marker_serialization() {
        let marker = Marker::new(
            "ethereum/historical/raw/blocks/blocks_0-999.parquet".to_string(),
            "collector-01".to_string(),
        );

        let bytes = marker.to_bytes().unwrap();
        let parsed = Marker::from_bytes(&bytes).unwrap();

        assert_eq!(parsed.file_path, marker.file_path);
        assert_eq!(parsed.uploader, marker.uploader);
    }

    #[test]
    fn test_manifest_add_ranges() {
        let mut manifest = S3Manifest::new();

        manifest.add_raw_blocks(0, 999);
        manifest.add_raw_blocks(1000, 1999);
        manifest.add_raw_blocks(0, 999); // Duplicate

        assert_eq!(manifest.raw_blocks.len(), 2);
        assert!(manifest.has_raw_blocks(0, 999));
        assert!(manifest.has_raw_blocks(1000, 1999));
        assert!(!manifest.has_raw_blocks(2000, 2999));
    }

    #[test]
    fn test_manifest_decoded_logs() {
        let mut manifest = S3Manifest::new();

        manifest.add_decoded_logs("v3", "Swap", 0, 999);
        manifest.add_decoded_logs("v3", "Burn", 0, 999);

        assert!(manifest.has_decoded_logs("v3", "Swap", 0, 999));
        assert!(manifest.has_decoded_logs("v3", "Burn", 0, 999));
        assert!(!manifest.has_decoded_logs("v3", "Swap", 1000, 1999));
    }

    #[test]
    fn test_marker_key() {
        let key = ManifestManager::marker_key("ethereum", "raw/blocks", 0, 999);
        assert_eq!(key, "ethereum/markers/raw/blocks/0_999.marker");
    }

    #[test]
    fn test_parse_marker_filename() {
        assert_eq!(parse_marker_filename("0_999.marker"), Some((0, 999)));
        assert_eq!(
            parse_marker_filename("1000_1999.marker"),
            Some((1000, 1999))
        );
        assert_eq!(parse_marker_filename("invalid.marker"), None);
    }

    use std::sync::Arc;

    use object_store::memory::InMemory;

    fn create_test_manager() -> ManifestManager {
        let store = Arc::new(InMemory::new());
        let s3 = S3Backend::from_store(store, "test-bucket".to_string());
        ManifestManager::new(s3, PathBuf::from("/tmp/test"), SyncConfig::default())
    }

    /// Write a marker file to the in-memory S3 backend at the given key.
    async fn write_marker_at(manager: &ManifestManager, key: &str) {
        let marker = Marker::new(format!("data/{}", key), "test".to_string());
        let data = marker.to_bytes().unwrap();
        manager.s3.write(key, &data).await.unwrap();
    }

    #[tokio::test]
    async fn test_aggregate_nested_markers_flat_parsing() {
        let manager = create_test_manager();

        // Write markers at the flat paths that S3 list returns relative to prefix
        let prefix = "eth/markers/decoded/logs";
        write_marker_at(&manager, &format!("{}/v3/Swap/0_999.marker", prefix)).await;
        write_marker_at(&manager, &format!("{}/v3/Swap/1000_1999.marker", prefix)).await;
        write_marker_at(&manager, &format!("{}/v3/Burn/0_999.marker", prefix)).await;
        write_marker_at(&manager, &format!("{}/v4/Transfer/500_1499.marker", prefix)).await;

        let mut results: Vec<(String, String, u64, u64)> = Vec::new();
        manager
            .aggregate_nested_markers(prefix, &mut |source, item, start, end| {
                results.push((source.to_string(), item.to_string(), start, end));
            })
            .await
            .unwrap();

        results.sort_by(|a, b| (&a.0, &a.1, a.2).cmp(&(&b.0, &b.1, b.2)));

        assert_eq!(results.len(), 4);
        assert_eq!(results[0], ("v3".to_string(), "Burn".to_string(), 0, 999));
        assert_eq!(results[1], ("v3".to_string(), "Swap".to_string(), 0, 999));
        assert_eq!(
            results[2],
            ("v3".to_string(), "Swap".to_string(), 1000, 1999)
        );
        assert_eq!(
            results[3],
            ("v4".to_string(), "Transfer".to_string(), 500, 1499)
        );
    }

    #[tokio::test]
    async fn test_aggregate_factory_markers_flat_parsing() {
        let manager = create_test_manager();

        let prefix = "eth/markers/factories";
        write_marker_at(
            &manager,
            &format!("{}/pool_collection/0_999.marker", prefix),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/pool_collection/1000_1999.marker", prefix),
        )
        .await;
        write_marker_at(&manager, &format!("{}/token_pairs/0_999.marker", prefix)).await;

        let mut results: Vec<(String, u64, u64)> = Vec::new();
        manager
            .aggregate_factory_markers(prefix, &mut |collection, start, end| {
                results.push((collection.to_string(), start, end));
            })
            .await
            .unwrap();

        results.sort_by(|a, b| (&a.0, a.1).cmp(&(&b.0, b.1)));

        assert_eq!(results.len(), 3);
        assert_eq!(results[0], ("pool_collection".to_string(), 0, 999));
        assert_eq!(results[1], ("pool_collection".to_string(), 1000, 1999));
        assert_eq!(results[2], ("token_pairs".to_string(), 0, 999));
    }

    #[tokio::test]
    async fn test_aggregate_eth_call_markers_regular_and_on_events() {
        let manager = create_test_manager();

        let prefix = "eth/markers/raw/eth_calls";
        // Regular: contract/function/start_end.marker
        write_marker_at(&manager, &format!("{}/0xabc/getPrice/0_999.marker", prefix)).await;
        write_marker_at(
            &manager,
            &format!("{}/0xabc/getPrice/1000_1999.marker", prefix),
        )
        .await;
        // On events: contract/function/on_events/start_end.marker
        write_marker_at(
            &manager,
            &format!("{}/0xdef/getLiquidity/on_events/0_999.marker", prefix),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/0xdef/getLiquidity/on_events/1000_1999.marker", prefix),
        )
        .await;

        let mut results: Vec<(String, String, u64, u64)> = Vec::new();
        manager
            .aggregate_eth_call_markers(prefix, &mut |contract, func, start, end| {
                results.push((contract.to_string(), func.to_string(), start, end));
            })
            .await
            .unwrap();

        results.sort_by(|a, b| (&a.0, &a.1, a.2).cmp(&(&b.0, &b.1, b.2)));

        assert_eq!(results.len(), 4);
        assert_eq!(
            results[0],
            ("0xabc".to_string(), "getPrice".to_string(), 0, 999)
        );
        assert_eq!(
            results[1],
            ("0xabc".to_string(), "getPrice".to_string(), 1000, 1999)
        );
        assert_eq!(
            results[2],
            (
                "0xdef".to_string(),
                "getLiquidity/on_events".to_string(),
                0,
                999
            )
        );
        assert_eq!(
            results[3],
            (
                "0xdef".to_string(),
                "getLiquidity/on_events".to_string(),
                1000,
                1999
            )
        );
    }

    #[tokio::test]
    async fn test_aggregate_raw_markers_propagates_errors() {
        // The InMemory store returns an empty list (not an error) for empty prefix,
        // so we test that the `?` propagation works by verifying non-error case succeeds.
        // The key behavioral change is that unwrap_or_default() is replaced with ?,
        // so real S3 errors bubble up instead of being silently swallowed.
        let manager = create_test_manager();

        // No markers written - should return Ok with empty results
        let mut results: Vec<(u64, u64)> = Vec::new();
        let result = manager
            .aggregate_raw_markers("nonexistent/prefix", |start, end| {
                results.push((start, end));
            })
            .await;

        assert!(result.is_ok());
        assert!(results.is_empty());
    }

    #[tokio::test]
    async fn test_aggregate_markers_full_chain() {
        let manager = create_test_manager();

        // Write markers for various data types
        let chain = "ethereum";

        // Raw blocks
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/blocks/0_999.marker", chain),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/blocks/1000_1999.marker", chain),
        )
        .await;

        // Raw logs
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/logs/0_999.marker", chain),
        )
        .await;

        // Decoded logs (nested: source/event/marker)
        write_marker_at(
            &manager,
            &format!("{}/markers/decoded/logs/v3/Swap/0_999.marker", chain),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/markers/decoded/logs/v3/Burn/0_999.marker", chain),
        )
        .await;

        // Factories
        write_marker_at(
            &manager,
            &format!("{}/markers/factories/pools/0_999.marker", chain),
        )
        .await;

        // Raw eth_calls with on_events
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/eth_calls/0xabc/slot0/0_999.marker", chain),
        )
        .await;
        write_marker_at(
            &manager,
            &format!(
                "{}/markers/raw/eth_calls/0xabc/slot0/on_events/0_999.marker",
                chain
            ),
        )
        .await;

        let manifest = manager.aggregate_markers(chain).await.unwrap();

        assert_eq!(manifest.raw_blocks.len(), 2);
        assert!(manifest.has_raw_blocks(0, 999));
        assert!(manifest.has_raw_blocks(1000, 1999));

        assert_eq!(manifest.raw_logs.len(), 1);
        assert!(manifest.has_raw_logs(0, 999));

        assert!(manifest.has_decoded_logs("v3", "Swap", 0, 999));
        assert!(manifest.has_decoded_logs("v3", "Burn", 0, 999));

        assert!(manifest.has_factories("pools", 0, 999));

        assert!(manifest.has_raw_eth_calls_granular("0xabc", "slot0", 0, 999));
        assert!(manifest.has_raw_eth_calls_granular("0xabc", "slot0/on_events", 0, 999));
    }

    #[tokio::test]
    async fn test_refresh_for_chain_rebuilds_from_markers_when_no_manifest() {
        let manager = create_test_manager();
        let chain = "ethereum";

        // Write some markers but NO manifest.json
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/blocks/0_999.marker", chain),
        )
        .await;
        write_marker_at(
            &manager,
            &format!("{}/markers/raw/blocks/1000_1999.marker", chain),
        )
        .await;

        // refresh_for_chain should detect missing manifest and rebuild from markers
        manager.refresh_for_chain(chain).await.unwrap();

        let cached = manager.cached_manifest_for(chain);
        assert!(cached.is_some());

        let manifest = cached.unwrap();
        assert_eq!(manifest.raw_blocks.len(), 2);
        assert!(manifest.has_raw_blocks(0, 999));
        assert!(manifest.has_raw_blocks(1000, 1999));

        // Verify manifest.json was saved to S3
        let key = ManifestManager::manifest_key(chain);
        let data = manager.s3.read(&key).await.unwrap();
        let saved_manifest = S3Manifest::from_bytes(&data).unwrap();
        assert_eq!(saved_manifest.raw_blocks.len(), 2);
    }

    #[tokio::test]
    async fn test_nested_markers_ignores_wrong_depth_entries() {
        let manager = create_test_manager();

        let prefix = "eth/markers/decoded/logs";
        // Correct depth (3 parts)
        write_marker_at(&manager, &format!("{}/v3/Swap/0_999.marker", prefix)).await;
        // Wrong depth (1 part - just a marker at root level)
        write_marker_at(&manager, &format!("{}/0_999.marker", prefix)).await;

        let mut results: Vec<(String, String, u64, u64)> = Vec::new();
        manager
            .aggregate_nested_markers(prefix, &mut |source, item, start, end| {
                results.push((source.to_string(), item.to_string(), start, end));
            })
            .await
            .unwrap();

        // Only the correctly-nested entry should be picked up
        assert_eq!(results.len(), 1);
        assert_eq!(results[0], ("v3".to_string(), "Swap".to_string(), 0, 999));
    }
}
