//! S3 manifest and marker system for distributed coordination.
//!
//! In a distributed deployment, multiple services need to know what data exists in S3.
//! This module provides:
//! - Marker files: Written after each upload to signal data availability
//! - S3Manifest: Aggregated view of all available data ranges
//! - ManifestManager: Handles manifest refresh and caching

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::RwLock;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

use super::s3::S3Backend;
use super::{StorageBackend, StorageError};
use crate::types::config::storage::SyncConfig;

/// Marker file written after each successful S3 upload.
///
/// Markers are small (~100 bytes) and signal that a particular range is available.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Marker {
    /// Unix timestamp when the upload completed
    pub uploaded_at: u64,
    /// Identifier of the service that uploaded the data
    pub uploader: String,
    /// S3 key of the uploaded file
    pub file_path: String,
}

impl Marker {
    /// Create a new marker.
    pub fn new(file_path: String, uploader: String) -> Self {
        Self {
            uploaded_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            uploader,
            file_path,
        }
    }

    /// Serialize to JSON bytes.
    pub fn to_bytes(&self) -> Result<Vec<u8>, StorageError> {
        serde_json::to_vec(self)
            .map_err(|e| StorageError::Serialization(e.to_string()))
    }

    /// Deserialize from JSON bytes.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, StorageError> {
        serde_json::from_slice(bytes)
            .map_err(|e| StorageError::Serialization(e.to_string()))
    }
}

/// Aggregated manifest of all available data in S3.
///
/// This is periodically generated by aggregating marker files and provides
/// a fast way to query what data exists without listing many marker files.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct S3Manifest {
    /// Unix timestamp when this manifest was generated
    pub generated_at: u64,
    /// Raw blocks ranges: [(start, end), ...]
    pub raw_blocks: Vec<(u64, u64)>,
    /// Raw logs ranges
    pub raw_logs: Vec<(u64, u64)>,
    /// Raw receipts ranges
    pub raw_receipts: Vec<(u64, u64)>,
    /// Raw eth_calls ranges
    pub raw_eth_calls: Vec<(u64, u64)>,
    /// Decoded logs by source/event: "source/event" -> [(start, end), ...]
    pub decoded_logs: HashMap<String, Vec<(u64, u64)>>,
    /// Decoded eth_calls by source/function
    pub decoded_eth_calls: HashMap<String, Vec<(u64, u64)>>,
    /// Factory ranges by collection name
    pub factories: HashMap<String, Vec<(u64, u64)>>,
}

impl S3Manifest {
    /// Create a new empty manifest.
    pub fn new() -> Self {
        Self {
            generated_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            ..Default::default()
        }
    }

    /// Serialize to JSON bytes.
    pub fn to_bytes(&self) -> Result<Vec<u8>, StorageError> {
        serde_json::to_vec_pretty(self)
            .map_err(|e| StorageError::Serialization(e.to_string()))
    }

    /// Deserialize from JSON bytes.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, StorageError> {
        serde_json::from_slice(bytes)
            .map_err(|e| StorageError::Serialization(e.to_string()))
    }

    /// Check if a raw blocks range exists in the manifest.
    pub fn has_raw_blocks(&self, start: u64, end: u64) -> bool {
        self.raw_blocks.iter().any(|(s, e)| *s == start && *e == end)
    }

    /// Check if a raw logs range exists.
    pub fn has_raw_logs(&self, start: u64, end: u64) -> bool {
        self.raw_logs.iter().any(|(s, e)| *s == start && *e == end)
    }

    /// Check if a raw receipts range exists.
    pub fn has_raw_receipts(&self, start: u64, end: u64) -> bool {
        self.raw_receipts.iter().any(|(s, e)| *s == start && *e == end)
    }

    /// Check if a raw eth_calls range exists.
    pub fn has_raw_eth_calls(&self, start: u64, end: u64) -> bool {
        self.raw_eth_calls.iter().any(|(s, e)| *s == start && *e == end)
    }

    /// Check if a decoded logs range exists for a source/event.
    pub fn has_decoded_logs(&self, source: &str, event: &str, start: u64, end: u64) -> bool {
        let key = format!("{}/{}", source, event);
        self.decoded_logs
            .get(&key)
            .map(|ranges| ranges.iter().any(|(s, e)| *s == start && *e == end))
            .unwrap_or(false)
    }

    /// Check if a factory range exists.
    pub fn has_factories(&self, collection: &str, start: u64, end: u64) -> bool {
        self.factories
            .get(collection)
            .map(|ranges| ranges.iter().any(|(s, e)| *s == start && *e == end))
            .unwrap_or(false)
    }

    /// Add a raw blocks range.
    pub fn add_raw_blocks(&mut self, start: u64, end: u64) {
        if !self.has_raw_blocks(start, end) {
            self.raw_blocks.push((start, end));
            self.raw_blocks.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a raw logs range.
    pub fn add_raw_logs(&mut self, start: u64, end: u64) {
        if !self.has_raw_logs(start, end) {
            self.raw_logs.push((start, end));
            self.raw_logs.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a raw receipts range.
    pub fn add_raw_receipts(&mut self, start: u64, end: u64) {
        if !self.has_raw_receipts(start, end) {
            self.raw_receipts.push((start, end));
            self.raw_receipts.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a raw eth_calls range.
    pub fn add_raw_eth_calls(&mut self, start: u64, end: u64) {
        if !self.has_raw_eth_calls(start, end) {
            self.raw_eth_calls.push((start, end));
            self.raw_eth_calls.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a decoded logs range.
    pub fn add_decoded_logs(&mut self, source: &str, event: &str, start: u64, end: u64) {
        let key = format!("{}/{}", source, event);
        let ranges = self.decoded_logs.entry(key).or_default();
        if !ranges.iter().any(|(s, e)| *s == start && *e == end) {
            ranges.push((start, end));
            ranges.sort_by_key(|(s, _)| *s);
        }
    }

    /// Add a factory range.
    pub fn add_factories(&mut self, collection: &str, start: u64, end: u64) {
        let ranges = self.factories.entry(collection.to_string()).or_default();
        if !ranges.iter().any(|(s, e)| *s == start && *e == end) {
            ranges.push((start, end));
            ranges.sort_by_key(|(s, _)| *s);
        }
    }
}

/// Manager for S3 manifest operations.
///
/// Handles:
/// - Reading/writing marker files
/// - Manifest aggregation from markers
/// - Caching and periodic refresh
pub struct ManifestManager {
    s3: S3Backend,
    local_base: PathBuf,
    config: SyncConfig,
    /// Cached manifest
    cached: RwLock<Option<S3Manifest>>,
    /// Last refresh time
    last_refresh: RwLock<Option<Instant>>,
}

impl ManifestManager {
    /// Create a new ManifestManager.
    pub fn new(s3: S3Backend, local_base: PathBuf, config: SyncConfig) -> Self {
        Self {
            s3,
            local_base,
            config,
            cached: RwLock::new(None),
            last_refresh: RwLock::new(None),
        }
    }

    /// Get access to the underlying S3 backend.
    pub fn s3_backend(&self) -> &S3Backend {
        &self.s3
    }

    /// Get the sync configuration.
    pub fn config(&self) -> &SyncConfig {
        &self.config
    }

    /// Get the local base path.
    pub fn local_base(&self) -> &PathBuf {
        &self.local_base
    }

    /// Get the marker key for a data file.
    ///
    /// Example: "ethereum/historical/raw/blocks/blocks_0-999.parquet"
    ///       -> "ethereum/markers/raw/blocks/0_999.marker"
    pub fn marker_key(chain: &str, data_type: &str, start: u64, end: u64) -> String {
        format!("{}/markers/{}/{}_{}.marker", chain, data_type, start, end)
    }

    /// Get the manifest key for a chain.
    pub fn manifest_key(chain: &str) -> String {
        format!("{}/manifest.json", chain)
    }

    /// Write a marker file after successful upload.
    pub async fn write_marker(
        &self,
        chain: &str,
        data_type: &str,
        start: u64,
        end: u64,
        file_path: &str,
        uploader: &str,
    ) -> Result<(), StorageError> {
        let marker = Marker::new(file_path.to_string(), uploader.to_string());
        let key = Self::marker_key(chain, data_type, start, end);
        let data = marker.to_bytes()?;

        self.s3.write(&key, &data).await?;

        tracing::debug!("Wrote marker: {}", key);
        Ok(())
    }

    /// Check if a marker exists.
    pub async fn has_marker(
        &self,
        chain: &str,
        data_type: &str,
        start: u64,
        end: u64,
    ) -> Result<bool, StorageError> {
        let key = Self::marker_key(chain, data_type, start, end);
        self.s3.exists(&key).await
    }

    /// Get the cached manifest (if available).
    pub fn cached_manifest(&self) -> Option<S3Manifest> {
        self.cached.read().unwrap().clone()
    }

    /// Check if the cached manifest is stale.
    pub fn is_stale(&self) -> bool {
        let refresh_interval = Duration::from_secs(self.config.manifest_refresh_secs);
        let last = self.last_refresh.read().unwrap();
        match *last {
            Some(t) => t.elapsed() > refresh_interval,
            None => true,
        }
    }

    /// Refresh the manifest from S3.
    ///
    /// Accepts an optional chain name. If provided, refreshes only that chain.
    /// If None, this is a no-op (caller should use `refresh_for_chain` directly).
    pub async fn refresh(&self) -> Result<(), StorageError> {
        // Without knowing which chain to refresh, we can only update the timestamp.
        // Callers should use refresh_for_chain() with a specific chain name.
        let mut last = self.last_refresh.write().unwrap();
        *last = Some(Instant::now());
        Ok(())
    }

    /// Refresh manifest for a chain by listing and aggregating markers.
    pub async fn refresh_from_markers(&self, chain: &str) -> Result<(), StorageError> {
        let manifest = self.aggregate_markers(chain).await?;

        // Update cache
        let mut cached = self.cached.write().unwrap();
        *cached = Some(manifest.clone());

        let mut last = self.last_refresh.write().unwrap();
        *last = Some(Instant::now());

        // Save to S3 for other services
        self.save_manifest(chain, &manifest).await?;

        Ok(())
    }

    /// Refresh the manifest for a specific chain.
    pub async fn refresh_for_chain(&self, chain: &str) -> Result<(), StorageError> {
        let key = Self::manifest_key(chain);

        match self.s3.read(&key).await {
            Ok(data) => {
                let manifest = S3Manifest::from_bytes(&data)?;
                let mut cached = self.cached.write().unwrap();
                *cached = Some(manifest);
            }
            Err(StorageError::NotFound(_)) => {
                // No manifest yet - start with empty
                let mut cached = self.cached.write().unwrap();
                *cached = Some(S3Manifest::new());
            }
            Err(e) => return Err(e),
        }

        let mut last = self.last_refresh.write().unwrap();
        *last = Some(Instant::now());

        Ok(())
    }

    /// Save the manifest to S3.
    pub async fn save_manifest(&self, chain: &str, manifest: &S3Manifest) -> Result<(), StorageError> {
        let key = Self::manifest_key(chain);
        let data = manifest.to_bytes()?;
        self.s3.write(&key, &data).await?;

        // Update cache
        let mut cached = self.cached.write().unwrap();
        *cached = Some(manifest.clone());

        tracing::info!("Saved manifest for chain {} ({} ranges total)", chain,
            manifest.raw_blocks.len() + manifest.raw_logs.len() + manifest.raw_receipts.len());

        Ok(())
    }

    /// Aggregate markers into a manifest for a chain.
    ///
    /// This reads all marker files and builds a complete manifest.
    pub async fn aggregate_markers(&self, chain: &str) -> Result<S3Manifest, StorageError> {
        let mut manifest = S3Manifest::new();

        // List and parse raw block markers
        let marker_prefix = format!("{}/markers/raw/blocks", chain);
        self.aggregate_raw_markers(&marker_prefix, |start, end| {
            manifest.add_raw_blocks(start, end);
        }).await?;

        // List and parse raw log markers
        let marker_prefix = format!("{}/markers/raw/logs", chain);
        self.aggregate_raw_markers(&marker_prefix, |start, end| {
            manifest.add_raw_logs(start, end);
        }).await?;

        // List and parse raw receipt markers
        let marker_prefix = format!("{}/markers/raw/receipts", chain);
        self.aggregate_raw_markers(&marker_prefix, |start, end| {
            manifest.add_raw_receipts(start, end);
        }).await?;

        // List and parse raw eth_calls markers
        let marker_prefix = format!("{}/markers/raw/eth_calls", chain);
        self.aggregate_raw_markers(&marker_prefix, |start, end| {
            manifest.add_raw_eth_calls(start, end);
        }).await?;

        Ok(manifest)
    }

    /// Helper to aggregate markers for a single data type.
    async fn aggregate_raw_markers<F>(&self, prefix: &str, mut add_fn: F) -> Result<(), StorageError>
    where
        F: FnMut(u64, u64),
    {
        let markers = self.s3.list(prefix).await?;

        for marker_file in markers {
            // Parse range from filename like "0_999.marker"
            if let Some(range) = parse_marker_filename(&marker_file) {
                add_fn(range.0, range.1);
            }
        }

        Ok(())
    }
}

/// Parse a marker filename like "0_999.marker" into (start, end).
fn parse_marker_filename(filename: &str) -> Option<(u64, u64)> {
    let name = filename.trim_end_matches(".marker");
    let parts: Vec<&str> = name.split('_').collect();
    if parts.len() == 2 {
        let start = parts[0].parse().ok()?;
        let end = parts[1].parse().ok()?;
        return Some((start, end));
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_marker_serialization() {
        let marker = Marker::new(
            "ethereum/historical/raw/blocks/blocks_0-999.parquet".to_string(),
            "collector-01".to_string(),
        );

        let bytes = marker.to_bytes().unwrap();
        let parsed = Marker::from_bytes(&bytes).unwrap();

        assert_eq!(parsed.file_path, marker.file_path);
        assert_eq!(parsed.uploader, marker.uploader);
    }

    #[test]
    fn test_manifest_add_ranges() {
        let mut manifest = S3Manifest::new();

        manifest.add_raw_blocks(0, 999);
        manifest.add_raw_blocks(1000, 1999);
        manifest.add_raw_blocks(0, 999); // Duplicate

        assert_eq!(manifest.raw_blocks.len(), 2);
        assert!(manifest.has_raw_blocks(0, 999));
        assert!(manifest.has_raw_blocks(1000, 1999));
        assert!(!manifest.has_raw_blocks(2000, 2999));
    }

    #[test]
    fn test_manifest_decoded_logs() {
        let mut manifest = S3Manifest::new();

        manifest.add_decoded_logs("v3", "Swap", 0, 999);
        manifest.add_decoded_logs("v3", "Burn", 0, 999);

        assert!(manifest.has_decoded_logs("v3", "Swap", 0, 999));
        assert!(manifest.has_decoded_logs("v3", "Burn", 0, 999));
        assert!(!manifest.has_decoded_logs("v3", "Swap", 1000, 1999));
    }

    #[test]
    fn test_marker_key() {
        let key = ManifestManager::marker_key("ethereum", "raw/blocks", 0, 999);
        assert_eq!(key, "ethereum/markers/raw/blocks/0_999.marker");
    }

    #[test]
    fn test_parse_marker_filename() {
        assert_eq!(parse_marker_filename("0_999.marker"), Some((0, 999)));
        assert_eq!(parse_marker_filename("1000_1999.marker"), Some((1000, 1999)));
        assert_eq!(parse_marker_filename("invalid.marker"), None);
    }
}
